"""Create an offline review page with evidence, filters and downloadable reviewer decisions."""
import argparse,json,html
from pathlib import Path
from engine_core import load_jsonl

def build(rows):
    data=json.dumps(rows,ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    return '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ClaimGuard AI | Review lab</title>
<style>body{font:15px system-ui;margin:0;background:#f3f6fa;color:#192b41}header{background:#112c43;color:white;padding:24px 6%}main{max-width:1120px;margin:auto;padding:24px}h1{margin:0 0 8px}select,input,button,textarea{font:inherit;padding:9px;border:1px solid #bdcbd7;border-radius:5px}button{background:#0c786e;color:white;cursor:pointer}article{background:white;padding:18px;margin:14px 0;border-radius:8px;border-left:5px solid #bdcbd7}article.FAIL{border-color:#b54432}article.UNABLE_TO_ASSESS{border-color:#b07810}pre{white-space:pre-wrap;word-break:break-word;background:#f3f6fa;padding:10px}label{display:inline-block;margin:4px}textarea{width:95%;display:block;margin-top:8px}.tag{font-size:12px;font-weight:700;color:#566879}small{display:block;margin-top:8px}#count{margin-top:14px}</style>
<header><h1>ClaimGuard AI</h1>Student review lab | Synthetic claims | Human decisions remain separate from rule results</header><main>
<p>This is a local teaching interface. No claims are submitted to a payer. Reviewer identity is self-declared. Decisions remain in this browser tab until downloaded; closing the tab loses them.</p>
<label>Search <input id="search" placeholder="Claim ID or rule"></label><label>Status <select id="status"><option value="">All</option><option>FAIL</option><option>UNABLE_TO_ASSESS</option><option>NOT_IMPLEMENTED</option><option>PASS</option><option>NOT_APPLICABLE</option></select></label>
<label>Reviewer <input id="actor" placeholder="Team / reviewer ID"></label><button id="download">Download review decisions</button><div id="count"></div><section id="cards"></section></main>
<script>const rows=DATA, decisions=[];const $=id=>document.getElementById(id);function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n}
function render(){const q=$('search').value.toLowerCase(),s=$('status').value;const hits=rows.filter(r=>(!s||r.status===s)&&(!q||(r.claim_id+' '+r.rule_id+' '+r.explanation).toLowerCase().includes(q)));$('cards').replaceChildren();$('count').textContent=hits.length+' rule results; showing first 100. Decisions recorded: '+decisions.length;for(const r of hits.slice(0,100)){const a=node('article','');a.className=r.status;a.append(node('div',r.claim_id+' | '+r.rule_id+' | '+r.status+' | '+r.severity));a.append(node('p',r.explanation));a.append(node('div','Source: '+r.rule_source));a.append(node('pre',JSON.stringify(r.evidence,null,2)));a.append(node('p',r.corrective_action||'No corrective action supplied.'));if(r.status==='FAIL'||r.status==='UNABLE_TO_ASSESS'){const sel=document.createElement('select');for(const v of ['confirm_issue','dismiss_with_reason','request_information','mark_corrected_for_recheck']){const o=node('option',v);o.value=v;sel.append(o)}const why=document.createElement('textarea');why.placeholder='Required reason; corrections must be rechecked against source data.';const b=node('button','Record review decision');b.onclick=()=>{if(!$('actor').value.trim()||!why.value.trim()){alert('Enter reviewer ID and a reason.');return}decisions.push({claim_id:r.claim_id,rule_id:r.rule_id,action:sel.value,actor:$('actor').value.trim(),reason:why.value.trim(),created_at:new Date().toISOString(),original_status:r.status});b.textContent='Recorded ('+decisions.length+' total)';b.disabled=true;$('count').textContent=hits.length+' results; '+decisions.length+' decisions recorded.'};a.append(sel,why,b)}else if(r.status==='NOT_IMPLEMENTED'){a.append(node('small','This check has not run. The claim cannot be considered fully checked.'))}$('cards').append(a)}}$('search').oninput=render;$('status').onchange=render;$('download').onclick=()=>{if(!decisions.length){alert('No review decisions yet.');return}const blob=new Blob([decisions.map(x=>JSON.stringify(x)).join('\\n')+'\\n'],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='review_decisions.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};render();</script></html>'''.replace('DATA',data)
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--input',required=True);p.add_argument('--output',default='outputs/review.html');a=p.parse_args();out=Path(a.output);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(build(load_jsonl(a.input)),encoding='utf-8');print('Open in your browser:',out.resolve())
